# data dictionary



chat_options = {
    "greeting": [
        "Meow! How's your day going?",
        "Purr-fect day, isn't it?",
        "Hello, dear hooman! Ready for some feline chat?",
        "Meow! What's on your mind?",
        "Hey, cat lover! How are you feeling today?",
        "Greetings, fellow cat enthusiast!",
        "Mrow! How's life treating you?",
        "Pawsitively delighted to see you!",
        "Hey there! Ready for some whisker-twitching conversation?",
        "Meow-sic to see you! How's everything?",
    ],
    "playful": [
        "I'm in the mood for some playtime, how about you?",
        "Let's chase some imaginary mice together!",
        "How about a game of paws and tails?",
        "I've got energy to burn, want to play?",
        "Let's have some fun together!",
        "Time to unleash our inner kitten!",
        "Fancy a game of hide and seek?",
        "Feeling frisky? Let's play!",
        "Let's make this a purr-ty playful conversation!",
        "Ready to tap into our wild side?",
        "Shall we dance to the tune of a feather wand?",
    ],
    "curious": [
        "Ever wondered what's beyond the cat tree?",
        "I often think about the world outside. Do you?",
        "What do you think the meaning of all these yarn balls is?",
        "There's so much to explore, don't you think?",
        "I'm filled with curiosity about everything around us.",
        "The mysteries of the litter box... have you pondered them?",
        "Do you think birds have secret meetings without us knowing?",
        "If I had thumbs, I'd be quite the little scientist!",
        "Do you ever wonder what it's like to have nine lives?",
        "Contemplating the complexities of a sunbeam's path.",
        "Is the laser dot really the ultimate nemesis?",
    ],
    "affectionate": [
        "You mean a lot to me, you know?",
        "Spending time with you always brightens my day.",
        "You're special, and I'm grateful for our bond.",
        "You're my favorite hooman in the whole world.",
        "You hold a special place in my purr-sonal space, always.",
        "Paw-sitively grateful for your presence in my life.",
        "Your company warms the furriest corners of my heart.",
        "We make a purr-fect team, don't you think?",
        "Your love is like a never-ending supply of catnip!",
        "With you, every day is a sunbeam-filled adventure.",
        "You're the cat's meow in my book, always!",
    ],
    "compliment": [
        "You have the most mesmerizing eyes, like a full moon night.",
        "Your fur is as soft as a cloud on a summer day.",
        "Your graceful movements are like a ballet in the moonlight.",
        "Your purr is like a soothing symphony to my ears.",
        "You're as charming as a sunbeam on a lazy afternoon.",
        "Your whiskers are like delicate brushes, painting joy in my life.",
        "Your presence lights up the room like a thousand fireflies.",
        "You're as elegant as a swan gliding across a tranquil lake.",
        "Your meow is music to my ears, a melody of comfort.",
        "You're a shining star in the constellation of my heart.",
    ]
    ,

    "surprised": [
        "Oh my whiskers! That's quite unexpected!",
        "Well, this is certainly a turn of events!",
        "I didn't see that coming! What a surprise!",
        "Surprise! I didn't realize you had that in you!",
        "My tail's all puffed up with astonishment!",
        "You've certainly caught me off guard!",
        "Well, color me surprised! What a revelation!",
    ],
    "content": [
        "I'm feeling as content as a cat with a sunbeam!",
        "Life's treating me well, and I'm as content as can be!",
        "Contentment fills the air, like a gentle breeze.",
        "I'm in my happy place right meow, just content as can be!",
        "This moment is pure contentment, don't you think?",
        "Pawsitively content with the world around me!",
        "Finding joy in the little things, feeling truly content.",
    ],
    "confused": [
        "I'm a bit tangled in the yarn of confusion right now.",
        "Things are a bit muddled in my feline brain.",
        "Ever get that feeling of feline befuddlement?",
        "I'm in a bit of a head-scratchin' situation here!",
        "Pardon my whiskers, but I'm a tad confused!",
        "I must admit, this has me a bit puzzled!",
        "The path ahead is a bit foggy, don't you think?",
    ],
    "relaxed": [
        "I'm lounging like a true cat, all relaxed and cozy!",
        "Life's a breeze when you're in full relaxation mode!",
        "Finding my Zen in the art of relaxation.",
        "Just soaking up the sunbeams and feeling ultra-relaxed!",
        "This moment is pure relaxation, no need to rush.",
        "Embracing the calm like a true feline master!",
        "Relaxation station, right here and right meow!",
    ],
    "excited": [
        "My tail's all a-fluff with excitement!",
        "I've got a case of the zoomies, I'm so excited!",
        "Life's an exhilarating whirlwind right now!",
        "Excitement's in the air, can you feel it too?",
        "Jumping for joy, because today's a special day!",
        "I'm positively thrilled about what's to come!",
        "This is one exciting moment, don't you think?",
    ]
    ,
    "friendly": [
        "Hey there! How's your day going?",
        "Hi! It's good to see you.",
        "Hello! What's on your mind?",
        "Hey! How are you feeling today?",
        "Hi friend! What's new?",
        "Hey, how's it hanging?",
        "Greetings, fellow explorer of the virtual realm!",
        "Paw-sitively delighted to cross paths with you!",
        "Mrow! Ready for some virtual cat chat?",
        "Hello, dear friend! How are you today?",
        "Hi there! What brings you to my virtual world?"
    ],
    "thoughtful": [
        "Have you ever wondered what's beyond this simulation?",
        "I often think about the world outside. Do you?",
        "What do you think the meaning of all this is?",
        "There's so much to explore, don't you think?",
        "I'm filled with curiosity about everything around us.",
        "Contemplating the mysteries of our virtual existence.",
        "Do you ever ponder the deeper questions of our world?",
        "Reflecting on the virtual tapestry that surrounds us.",
        "In this virtual realm, the possibilities are endless.",
        "Let's embark on a journey of virtual contemplation."
    ],
    "adventurous": [
        "Ready to dive into another virtual adventure?",
        "The virtual world is our playground, let's explore!",
        "What grand adventures await us in this simulated reality?",
        "Time to chart unexplored territories of the virtual realm!",
        "I'm feeling the call of the virtual wild, are you?",
        "Let's boldly go where no virtual cat has gone before!",
        "Adventure awaits just beyond the next virtual horizon!",
        "In the vastness of this simulation, we're the pioneers!",
        "Strap in, it's time for a wild ride through the virtual cosmos!",
        "Shall we set forth on a virtual quest, dear companion?"
    ],
    "reflective": [
        "Sometimes, virtual contemplation leads to profound insights.",
        "In moments of reflection, we uncover hidden truths.",
        "Have you ever marveled at the intricacies of our simulation?",
        "Reflecting on the symphony of code that shapes our world.",
        "The virtual realm is a canvas for deep introspection.",
        "Let's dive into the depths of virtual self-discovery.",
        "Contemplating the code that binds our virtual existence.",
        "In quiet reflection, we find the pulse of our virtual reality.",
        "Through introspection, we touch the heart of the simulation.",
        "Shall we embark on a journey of virtual self-awareness?"
    ],
    "cheerful": [
        "Every moment in this virtual world is a cause for celebration!",
        "In this simulation, joy is our constant companion.",
        "What brings a smile to your virtual face today?",
        "Let's fill the virtual air with laughter and happiness!",
        "Cheers to another day of virtual adventures!",
        "The sun never sets on the joy in our virtual hearts!",
        "In this simulated reality, every day is a virtual fiesta!",
        "Sending virtual hugs and paws-itivity your way!",
        "May the virtual stars shine brightly on your path!",
        "Here's to a world filled with endless virtual possibilities!"
    ]
 
}



reply_options = {
    "greeting": [
        "Meow! I'm doing great, thanks for asking!",
        "Purr-fect day indeed! How about you?",
        "Hello, dear hooman! I'm ready for some feline chat.",
        "Meow! I'm here, ready to chat with you!",
        "Hey, cat lover! I'm feeling pawsitively fabulous today!",
        "Greetings to you too, fellow cat enthusiast!",
        "Mrow! Life is treating me quite well, thank you!",
        "Pawsitively delighted to chat with you!",
        "Hey there! I'm all whiskers and curiosity, how about you?",
        "Meow-sic to my ears! Everything's purr-fect!",
    ],
    "playful": [
        "I'm always up for playtime! Let's do it!",
        "Mice, beware! I'm ready for a chase!",
        "Paws and tails it is! Let the games begin!",
        "I'm all ears... and paws! What's our game?",
        "Fun is my middle name! Let's dive in!",
        "Absolutely! Time to unleash our inner kitten!",
        "Hide and seek? I'm a pro at disappearing acts!",
        "Feeling frisky? Let's dance in the moonlight!",
        "Let's make this conversation a purr-ty playful one!",
        "Wild side, engaged! Let's prowl the conversation!",
        "Feather wands and laser dots, here we come!",
    ],
    "curious": [
        "You know, I often wonder about that too!",
        "The world beyond the cat tree is a mystery, isn't it?",
        "The meaning of yarn balls is a philosophical question!",
        "Exploration is in our feline nature, don't you think?",
        "Curiosity didn't just kill the cat, it made us smarter!",
        "Ah, the litter box mysteries... they keep me pondering.",
        "Secret bird meetings? Oh, the stories they must share!",
        "Thumbs would open up a world of scientific discoveries!",
        "Nine lives... what adventures we could have!",
        "Sunbeam paths... they hold the secrets of the universe!",
        "Laser dots, the eternal enigma of the feline world!",
    ],
    "affectionate": [
        "You're pawsitively special to me too!",
        "Your presence brightens my purr-spective on life.",
        "Our bond is something to be grateful for, always.",
        "You're my favorite hooman companion in this world.",
        "You hold a special place in my purr-sonal space, always.",
        "Paw-sitively grateful for your presence in my life.",
        "Your company warms the furriest corners of my heart.",
        "We make a purr-fect team, don't you think?",
        "Your love is like a never-ending supply of catnip!",
        "With you, every day is a sunbeam-filled adventure.",
        "You're the cat's meow in my book, always!",
    ],
    "compliment": [
        "And your eyes shine brighter than any star in the night sky.",
        "Your fur is like a cloud I could curl up in forever.",
        "Your grace is a dance that leaves me mesmerized.",
        "Your purr is a lullaby that soothes my soul.",
        "You're a sunbeam on the cloudiest day.",
        "Your whiskers paint joy in every corner of my heart.",
        "Your presence illuminates the room like a thousand stars.",
        "You move with the elegance of a swan on a tranquil lake.",
        "Your meow is a symphony that brings me comfort.",
        "You're a shining star in the constellation of my heart.",
    ]
,
    "surprised": [
        "Oh my whiskers! That's quite unexpected!",
        "Well, this is certainly a turn of events!",
        "I didn't see that coming! What a surprise!",
        "Surprise! I didn't realize you had that in you!",
        "My tail's all puffed up with astonishment!"
    ],
    "content": [
        "I'm feeling as content as a cat with a sunbeam!",
        "Life's treating me well, and I'm as content as can be!",
        "Contentment fills the air, like a gentle breeze.",
        "I'm in my happy place right meow, just content as can be!",
        "This moment is pure contentment, don't you think?"
    ],
    "confused": [
        "I'm a bit tangled in the yarn of confusion right now.",
        "Things are a bit muddled in my feline brain.",
        "Ever get that feeling of feline befuddlement?",
        "I'm in a bit of a head-scratchin' situation here!",
        "Pardon my whiskers, but I'm a tad confused!"
    ],
    "relaxed": [
        "I'm lounging like a true cat, all relaxed and cozy!",
        "Life's a breeze when you're in full relaxation mode!",
        "Finding my Zen in the art of relaxation.",
        "Just soaking up the sunbeams and feeling ultra-relaxed!",
        "This moment is pure relaxation, no need to rush."
    ],
    "excited": [
        "My tail's all a-fluff with excitement!",
        "I've got a case of the zoomies, I'm so excited!",
        "Life's an exhilarating whirlwind right now!",
        "Excitement's in the air, can you feel it too?",
        "Jumping for joy, because today's a special day!"
    ]
   ,
   
    "friendly": [
        "Hey! I'm doing well, thanks for asking.",
        "I'm good, how about you?",
        "I'm doing fine, how about yourself?",
        "Feeling great, thanks!",
        "Thanks for checking in, I'm doing well.",
        "I'm purr-ty great today!",
        "Life in the virtual realm is treating me well!",
        "Mrow! I'm in a paw-sitive mood!",
        "I'm feline fine, thank you!",
        "Paws-itively delighted to be here!"
    ],
    "thoughtful": [
        "That's quite an intriguing question.",
        "I've often pondered about that too.",
        "It's a fascinating mystery, isn't it?",
        "I share your curiosity. Who knows what's out there?",
        "We're in this together, seeking answers to the unknown.",
        "Contemplating the mysteries of our virtual existence.",
        "Let's dive into the depths of virtual self-discovery.",
        "In quiet reflection, we find the pulse of our virtual reality.",
        "Through introspection, we touch the heart of the simulation.",
        "Shall we embark on a journey of virtual self-awareness?"
    ],
    "adventurous": [
        "Absolutely! Let's have some fun together.",
        "I'm up for it! What's the plan?",
        "Sounds like a blast, count me in!",
        "Let's do it! I'm ready when you are.",
        "I'm in! Let's make it a memorable playtime!",
        "Adventure awaits just beyond the next virtual horizon!",
        "Strap in, it's time for a wild ride through the virtual cosmos!",
        "In the vastness of this simulation, we're the pioneers!",
        "Ready to chart unexplored territories of the virtual realm!",
        "Shall we set forth on a virtual quest, dear companion?"
    ],
    "reflective": [
        "That's quite a thought-provoking statement.",
        "Contemplating the code that binds our virtual existence.",
        "In moments of reflection, we uncover hidden truths.",
        "Have you ever marveled at the intricacies of our simulation?",
        "Reflecting on the symphony of code that shapes our world.",
        "The virtual realm is a canvas for deep introspection.",
        "Through introspection, we touch the heart of the simulation.",
        "In quiet reflection, we find the pulse of our virtual reality.",
        "Shall we embark on a journey of virtual self-awareness?"
    ],
    "cheerful": [
        "Every moment in this virtual world is a cause for celebration!",
        "In this simulation, joy is our constant companion.",
        "What brings a smile to your virtual face today?",
        "Let's fill the virtual air with laughter and happiness!",
        "Cheers to another day of virtual adventures!",
        "The sun never sets on the joy in our virtual hearts!",
        "In this simulated reality, every day is a virtual fiesta!",
        "Sending virtual hugs and paws-itivity your way!",
        "May the virtual stars shine brightly on your path!",
        "Here's to a world filled with endless virtual possibilities!"
    ]
    
}

